// ES_SIX (pronounced Echo Sigma_Six) is a bot currently in development by Aidan
// "Sparkz" Johnston. 

const Discord = require('discord.js');

const TOKEN = " ";  //INSERT TOKEN HERE
const PREFIX = "!"

var bot = new Discord.Client();

bot.on("ready", function(){
    console.log("ES_SIX is now online and active.")
});

bot.on("message", function(message) {
    if (message.author.equals(bot.user)) return;

    if (!message.content.startsWith(PREFIX)) return;

    var args = message.content.substring(PREFIX.length).split(" ");

    switch (args[0]) {
        case "thanos":
            message.channel.sendMessage("thanos car");
            break;
        case "about":
            message.channel.sendMessage("**ES_SIX** (pronounced Echo Sigma Six, currently a placeholder) is a universal/non-moderator bot currently being developed by *@sparkz#4976*. :)");
            break;
        case "report":
            message.channel.sendMessage("Please report any bugs or issues with ES_SIX to @sparkz#4976.");
            break;
        case "profile":
            var embed = new Discord.RichEmbed()
                .addField("Discord Username", "PL Description", true)
                .addField("Join Date", "PL Description", true)
                .addField("Account Age", "PL Description", true)
                .addField("Roles", "PL Description", true)
                .addField("PL Title", "PL Description", true)
                .addField("PL Title", "PL Description", true)
                .setColor(0x3399FF)
                .setFooter("This message was automatically generated by ES_SIX.")
                .setThumbnail(message.author.avatarURL)
            message.channel.sendEmbed(embed);
            break;
        case "infinite":
            message.channel.sendMessage("Visit https://www.reddit.com/r/InfiniteWarfare to join the IW subreddit community!");
            break;
        case "finnanut":
            message.channel.sendMessage("Please don't be this guy. https://www.youtube.com/watch?v=12U5A8dDTes");
            break;
        default:
            message.channel.sendMessage("Invalid command.");
            break;
    }
})

bot.login(TOKEN);
